# Generated by Django 5.2.7 on 2025-10-31 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_options_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, help_text="User's WhatsApp number with country code (e.g., +55 11 98765-4321)", max_length=20, null=True),
        ),
    ]
