# Generated by Django 5.2.7 on 2026-10-07 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter (gateway, 200+ models)'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], default='openai', max_length=20)),
                ('chat_model', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('embedding_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter (gateway, 200+ models)'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], default='openai', max_length=20)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=120)),
                ('preset', models.CharField(choices=[('didatico', 'Didactic'), ('analitico', 'Analytic'), ('conciso', 'Concise'), ('personalizado', 'Custom')], default='didatico', max_length=20)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('neutro', 'Neutral'), ('informal', 'Informal')], default='neutro', max_length=20)),
                ('length', models.CharField(choices=[('curto', 'Short'), ('medio', 'Medium'), ('longo', 'Long')], default='medio', max_length=20)),
                ('language', models.CharField(choices=[('pt-br', 'Portuguese (Brazil)'), ('en', 'English'), ('es', 'Spanish')], default='pt-br', max_length=10)),
                ('answer_format', models.CharField(choices=[('prosa', 'Prose'), ('topicos', 'Bullet points'), ('passo_a_passo', 'Step by step')], default='prosa', max_length=20)),
                ('detail_level', models.CharField(choices=[('iniciante', 'Beginner'), ('intermediario', 'Intermediate'), ('avancado', 'Advanced')], default='intermediario', max_length=20)),
                ('extra_instructions', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspace.notebook')),
            ],
            options={
                'verbose_name': 'notebook settings',
                'verbose_name_plural': 'notebook settings',
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter (gateway, 200+ models)'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], max_length=20)),
                ('base_url', models.CharField(blank=True, default='', max_length=300)),
                ('model_list', models.JSONField(blank=True, default=list)),
                ('models_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider config',
                'verbose_name_plural': 'provider configs',
                'ordering': ['provider'],
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter (gateway, 200+ models)'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], max_length=20)),
                ('ciphertext', models.TextField()),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'provider credential',
                'verbose_name_plural': 'provider credentials',
                'ordering': ['provider'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
