# Generated by Django 5.2.7 on 2026-10-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooksettings',
            name='answer_format',
            field=models.CharField(choices=[('prosa', 'Prose'), ('topicos', 'Bullet points'), ('passo_a_passo', 'Step by step')], default='prosa', max_length=20, verbose_name='Answer format'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='chat_model',
            field=models.CharField(default='gpt-4o-mini', max_length=120, verbose_name='Chat model'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='chat_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter (gateway, 200+ models)'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], default='openai', max_length=20, verbose_name='Chat provider'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='detail_level',
            field=models.CharField(choices=[('iniciante', 'Beginner'), ('intermediario', 'Intermediate'), ('avancado', 'Advanced')], default='intermediario', max_length=20, verbose_name='Detail level'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='embedding_model',
            field=models.CharField(default='text-embedding-3-small', max_length=120, verbose_name='Embedding model'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='embedding_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter (gateway, 200+ models)'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], default='openai', max_length=20, verbose_name='Embedding provider'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='extra_instructions',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Extra instructions'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='language',
            field=models.CharField(choices=[('pt-br', 'Portuguese (Brazil)'), ('en', 'English'), ('es', 'Spanish')], default='pt-br', max_length=10, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='length',
            field=models.CharField(choices=[('curto', 'Short'), ('medio', 'Medium'), ('longo', 'Long')], default='medio', max_length=20, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='preset',
            field=models.CharField(choices=[('didatico', 'Didactic'), ('analitico', 'Analytic'), ('conciso', 'Concise'), ('personalizado', 'Custom')], default='didatico', max_length=20, verbose_name='Preset'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='tone',
            field=models.CharField(choices=[('formal', 'Formal'), ('neutro', 'Neutral'), ('informal', 'Informal')], default='neutro', max_length=20, verbose_name='Tone'),
        ),
    ]
