# Generated by Django 5.2.7 on 2026-10-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_field_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebooksettings',
            name='chat_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], default='openai', max_length=20, verbose_name='Chat provider'),
        ),
        migrations.AlterField(
            model_name='notebooksettings',
            name='embedding_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], default='openai', max_length=20, verbose_name='Embedding provider'),
        ),
        migrations.AlterField(
            model_name='providerconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude'), ('gemini', 'Google Gemini'), ('deepseek', 'DeepSeek'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('xai', 'xAI (Grok)'), ('perplexity', 'Perplexity'), ('together', 'Together AI'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama'), ('lmstudio', 'LM Studio'), ('llamacpp', 'llama.cpp')], max_length=20),
        ),
    ]
