# Generated by Django 5.2.7 on 2026-10-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_nvidia_huggingface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providercredential',
            name='last_four',
        ),
    ]
