# Generated by Django 5.2.7 on 2026-10-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='workspace.notebook')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('streaming', 'streaming'), ('complete', 'complete'), ('stopped', 'stopped'), ('error', 'error')], default='complete', max_length=10)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('source_filter', models.JSONField(blank=True, null=True)),
                ('not_found', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rag.conversation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MessageCitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.PositiveSmallIntegerField()),
                ('source_title', models.CharField(max_length=255)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('cited', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0.0)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sources.chunk')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='rag.message')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sources.source')),
            ],
            options={
                'ordering': ['n'],
                'constraints': [models.UniqueConstraint(fields=('message', 'n'), name='citation_unique_n_per_message')],
            },
        ),
    ]
