# Generated by Django 5.2.7 on 2026-10-07 21:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
import sources.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        # pgvector must exist before any vector column (spec D1).
        VectorExtension(),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('text', 'Text')], max_length=10, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('file', models.FileField(blank=True, storage=sources.storage.get_source_storage, upload_to=sources.storage.source_upload_to)),
                ('text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workspace.notebook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=120)),
                ('embedding_dim', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(null=True)),
                ('search_config', models.CharField(default='simple', max_length=20)),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='workspace.notebook')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='sources.source')),
            ],
            options={
                'ordering': ['source_id', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.UniqueConstraint(fields=('notebook', 'content_hash'), name='source_unique_content_per_notebook'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['notebook', 'embedding_model'], name='chunk_notebook_model_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('source', 'order'), name='chunk_unique_order_per_source'),
        ),
    ]
