# Generated by Django 5.2.7 on 2026-10-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='kind',
            field=models.CharField(choices=[('pdf', 'PDF'), ('text', 'Text'), ('markdown', 'Markdown')], max_length=10, verbose_name='Type'),
        ),
    ]
